import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/AuthProvider/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Geology Finder',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ""}>
        <AuthProvider>
          <div className="max-w-screen-xl min-h-screen px-3 bg-amber-200/[0.1] mx-auto my-0">
            <Navbar/>
            { children }
            <Footer/>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
